### ISSUE TITLE
Issue in sending dlrr block

### ISSUE THREAD

**Issue by ybybwdwd** [versatica/mediasoup#1211] opened 2023-11-07 11:39 UTC
In [rfc3611](https://www.rfc-editor.org/rfc/rfc3611#section-4.5) ，the dlrr block consists of one or more 3 word sub-
   blocks: one sub-block per Receiver Report.Report. but in mediasoup they are in different blocks.

The client may only resolve 1 block.
rfc3611:
![image](https://github.com/versatica/mediasoup/assets/49260497/04fbc5ca-9428-48b2-b82c-f09ddab54885)

mediasoup:
![image](https://github.com/versatica/mediasoup/assets/49260497/7f971efb-b797-404f-b396-78d47b61745b)

**Comment by ibc** [comment] 2023-11-08 12:29
Thanks, will fix soon.

**Comment by ibc** [comment] 2023-11-21 12:54
PR done: https://github.com/versatica/mediasoup/pull/1234

**Comment by ibc** [comment] 2023-11-21 15:12
Released in mediasoup node 3.13.4. Thanks a lot for the report @ybybwdwd

**Comment by ybybwdwd** [comment] 2023-11-22 01:45
> PR done: #1234

This fix is good, but I think this issue is sending dlrr instead of parsing the received dlrr

**Comment by ybybwdwd** [comment] 2023-11-22 07:09
![image](https://github.com/versatica/mediasoup/assets/49260497/19e26cfa-715c-4912-8783-d633015ab322)
libwebrtc parse 1 dlrr block

**Comment by ibc** [comment] 2023-11-22 09:44
@ybybwdwd, mediasoup is correctly generating RTCP Extended Report (XR) packets that include an Extended Report DLRR block with N sub-blocks. To verify it check `TestXr.cpp` file in `worker/test/`:

This is a XR packet with an Extended Report DLRR block that contains 2 sub-blocks (AKA ssrc infos):

```c++
uint8_t buffer[] =
{
	0xa0, 0xcf, 0x00, 0x09, // Padding, Type: 207 (XR), Length: 9
	0x5d, 0x93, 0x15, 0x34, // Sender SSRC: 0x5d931534
	// Extended Report DLRR
	0x05, 0x00, 0x00, 0x06, // BT: 5 (DLRR), Block Length: 6
	0x11, 0x12, 0x13, 0x14, // SSRC 1
	0x00, 0x11, 0x00, 0x11, // LRR 1
	0x11, 0x00, 0x11, 0x00, // DLRR 1
	0x21, 0x22, 0x23, 0x24, // SSRC 2
	0x00, 0x22, 0x00, 0x22, // LRR 2
	0x22, 0x00, 0x22, 0x00, // DLRR 2
	0x00, 0x00, 0x00, 0x04 // Padding (4 bytes)
};
```

The test parses it. The parsed packet's dump is as follows:

```
RTC::RTCP::XR::Dump() | <ExtendedReportPacket>
RTC::RTCP::XR::Dump() |   ssrc: 1569920308
RTC::RTCP::XrDelaySinceLastRr::Dump() | <DelaySinceLastRr>
RTC::RTCP::XrDelaySinceLastRr::Dump() |   block type : 5
RTC::RTCP::XrDelaySinceLastRr::Dump() |   reserved   : 0
RTC::RTCP::XrDelaySinceLastRr::Dump() |   length     : 6
RTC::RTCP::XrDelaySinceLastRr::Dump() |   <SsrcInfo>
RTC::RTCP::XrDelaySinceLastRr::Dump() |     ssrc : 286397204
RTC::RTCP::XrDelaySinceLastRr::Dump() |     lrr  : 1114129
RTC::RTCP::XrDelaySinceLastRr::Dump() |     dlrr : 285217024
RTC::RTCP::XrDelaySinceLastRr::Dump() |   <SsrcInfo>
RTC::RTCP::XrDelaySinceLastRr::Dump() |   <SsrcInfo>
RTC::RTCP::XrDelaySinceLastRr::Dump() |     ssrc : 555885348
RTC::RTCP::XrDelaySinceLastRr::Dump() |     lrr  : 2228258
RTC::RTCP::XrDelaySinceLastRr::Dump() |     dlrr : 570434048
RTC::RTCP::XrDelaySinceLastRr::Dump() |   <SsrcInfo>
RTC::RTCP::XrDelaySinceLastRr::Dump() | </DelaySinceLastRr>
RTC::RTCP::XR::Dump() | </ExtendedReportPacket>
```

Then we serialize the packet into a buffer and parse that buffer again in packet2, whose dump is exactly the same:

```
RTC::RTCP::XR::Dump() | <ExtendedReportPacket>
RTC::RTCP::XR::Dump() |   ssrc: 1569920308
RTC::RTCP::XrDelaySinceLastRr::Dump() | <DelaySinceLastRr>
RTC::RTCP::XrDelaySinceLastRr::Dump() |   block type : 5
RTC::RTCP::XrDelaySinceLastRr::Dump() |   reserved   : 0
RTC::RTCP::XrDelaySinceLastRr::Dump() |   length     : 6
RTC::RTCP::XrDelaySinceLastRr::Dump() |   <SsrcInfo>
RTC::RTCP::XrDelaySinceLastRr::Dump() |     ssrc : 286397204
RTC::RTCP::XrDelaySinceLastRr::Dump() |     lrr  : 1114129
RTC::RTCP::XrDelaySinceLastRr::Dump() |     dlrr : 285217024
RTC::RTCP::XrDelaySinceLastRr::Dump() |   <SsrcInfo>
RTC::RTCP::XrDelaySinceLastRr::Dump() |   <SsrcInfo>
RTC::RTCP::XrDelaySinceLastRr::Dump() |     ssrc : 555885348
RTC::RTCP::XrDelaySinceLastRr::Dump() |     lrr  : 2228258
RTC::RTCP::XrDelaySinceLastRr::Dump() |     dlrr : 570434048
RTC::RTCP::XrDelaySinceLastRr::Dump() |   <SsrcInfo>
RTC::RTCP::XrDelaySinceLastRr::Dump() | </DelaySinceLastRr>
RTC::RTCP::XR::Dump() | </ExtendedReportPacket>
```

So everything is good from parsing and serialization point of view. So please be more specific in the problem you are reporting. Just imagine that there is a bug in libwebrtc parsing. Do you literally mean that mediasoup is generating RTCP XR packets that contain more than a Extended Report DLRR block? And if so, why is that wrong?

**Comment by ibc** [comment] 2023-11-22 09:45
I'll reopen this issue for now until we clarify what the real issue is.

**Comment by ibc** [comment] 2023-11-22 09:48
To be clear: mediasoup does NOT generate RTCP Extended Report packets:

```c++
$ ack ExtendedReportPacket
Transport.cpp
2077:				auto* xr = static_cast<RTC::RTCP::ExtendedReportPacket*>(packet);

RTCP/Packet.cpp
142:						current = ExtendedReportPacket::Parse(data, packetLen);

RTCP/XR.cpp
57:		ExtendedReportPacket* ExtendedReportPacket::Parse(const uint8_t* data, size_t len)
72:			std::unique_ptr<ExtendedReportPacket> packet(new ExtendedReportPacket(header));
101:		size_t ExtendedReportPacket::Serialize(uint8_t* buffer)
120:		void ExtendedReportPacket::Dump() const
124:			MS_DUMP("<ExtendedReportPacket>");
130:			MS_DUMP("</ExtendedReportPacket>");
```

mediasoup just parses received RTCP XR packets but does NOT generate/forward them to endpoints.

**Comment by ibc** [comment] 2023-11-22 12:42
We are definitely creating XR packets into the Compound Packets that we generate, and we add DLRR blocks into them:

```c++
bool CompoundPacket::Add(
  SenderReport* senderReport, SdesChunk* sdesChunk, DelaySinceLastRr* delaySinceLastRrReport)
{
```

```c++
bool CompoundPacket::Add(
  std::vector<SenderReport*>& senderReports,
  std::vector<SdesChunk*>& sdesChunks,
  std::vector<DelaySinceLastRr*>& delaySinceLastRrReports)
{
```

```c++
void CompoundPacket::AddDelaySinceLastRr(DelaySinceLastRr* report)
{
	MS_TRACE();

	this->xrPacket.AddReport(report);
}
```

The problem is that libwebrtc ignores/discards DDLR blocks if it found already one (as shown here https://github.com/versatica/mediasoup/issues/1211#issuecomment-1822222463). What I don't know is if libwebrtc discards:
1. all DLRR blocks in a XR packet other than the first one, or
2. all DLRR blocks in a compound packet other than the first DLRR block in the first XR packet.

In other words:

- Are we adding more than a single XR packet into our Compound Packets? I think we don't because our `CompoundPacket` class has a `this->xrPacket` so clearly we only introduce one XR packet into it.
- Are we adding more than a single DLRR block into that XR packet? The API we expose in `CompoundPacket` clearly allows it, so probably we are doing it. The thing is, should we instead have a single DLRR block in our XR packet and add N subblocks into it (AKA sssrc infos)? Probably yes.
- However, why? Does the spec mandate that? or is it a libwebrtc bad assumption? Even if the latter, we should probably have a single DLRR block with N subblocks.

And yes, we are creating multiple `DLRR` blocks because each `XxxxConsumer::GetRtcp()` method literally creates one:

<img width="754" alt="CleanShot-2023-11-22-at-13 47 42@2x" src="https://github.com/versatica/mediasoup/assets/16191/beaae631-4514-4c10-a63b-52fce7dd33f7">

**Comment by ybybwdwd** [comment] 2023-11-22 16:10
> The problem is that libwebrtc ignores/discards DDLR blocks if it found already one (as shown here https://github.com/versatica/mediasoup/issues/1211#issuecomment-1822222463). What I don't know is if libwebrtc discards:
> 
> all DLRR blocks in a XR packet other than the first one, or
> all DLRR blocks in a compound packet other than the first DLRR block in the first XR packet.

If there are multiple XR packets in a Compound Packet, libwebrtc only parses the first block in each XR packets.
see:
https://webrtc.googlesource.com/src/+/refs/heads/main/modules/rtp_rtcp/source/rtcp_receiver.cc#373
https://webrtc.googlesource.com/src/+/refs/heads/main/modules/rtp_rtcp/source/rtcp_packet/extended_reports.cc#179

> Are we adding more than a single DLRR block into that XR packet? The API we expose in CompoundPacket clearly allows it, so probably we are doing it. The thing is, should we instead have a single DLRR block in our XR packet and add N subblocks into it (AKA sssrc infos)? Probably yes.

That's what this issue is about.
The RFC3611 doesn't seem to mandate that each XR packet can only have one DDLR block, but libwebrtc thinks it makes no sense to have multiple blocks of the same type in an XR packet
see:
https://codereview.webrtc.org/2378113002

**Comment by ibc** [comment] 2023-11-22 16:19
Thanks. I'm fixing it for DLRR first, then will check if other reports need same changes/optimizations.

**Comment by jmillan** [comment] 2023-11-22 16:33
> Thanks. I'm fixing it for DLRR first

What are you fixing? Having a single item in the DLRR packet and creating N DLRR packets instead so libwebrtc can handle it?

**Comment by ibc** [comment] 2023-11-22 16:38
> > Thanks. I'm fixing it for DLRR first
> 
> What are you fixing? Having a single item in the DLRR packet and creating N DLRR packets instead so libwebrtc can handle it?

No, the opposite: https://github.com/versatica/mediasoup/pull/1237

**Closed as completed** 2023-11-22 17:28 UTC
Labels: bug
