### ISSUE TITLE
[Windows] Parent project GUID  not found in "mediasoup-worker" project dependency section

### ISSUE THREAD

**Issue by EyalSi** [versatica/mediasoup#345] opened 2019-11-18 17:01 UTC
Hi,

I'm getting the following error when trying to compile mediasoup.

- Operating system: Windows 10
- Node version: v10.11.0
- npm version: 6.5.0
- gcc/clang version:
- visual studio: 2017
- mediasoup version: 3.3.2

Installed:
Visual studio 2017 with Windows SDK
trying to execute:
"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\MSBuild.exe" ./worker/mediasoup-worker.sln /p:Configuration=Release

Results in the following error:
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
Build started 11/18/2019 6:52:46 PM.
d:\Data\mediasoup\worker\mediasoup-worker.sln(44): Solution file error MSB5011: Parent project GUID
 not found in "mediasoup-worker" project dependency section.

Build FAILED.

  d:\Data\mediasoup\worker\mediasoup-worker.sln(44): Solution file error MSB5011: Parent project GU
ID not found in "mediasoup-worker" project dependency section.

0 Warning(s)
1 Error(s)

Below is the SLN file I have. any idea what is the issue?
10x!!

SLN file content:

Microsoft Visual Studio Solution File, Format Version 12.00

\# Visual Studio 2017

Project("{2150E333-8FDC-42A3-9474-1A3956D46DE8}") = "(abseil-cpp)", "..\deps\libwebrtc\deps\abseil-cpp", "{9DC36AD0-A741-FFB2-D815-5B81F7BAF592}"

EndProject

Project("{2150E333-8FDC-42A3-9474-1A3956D46DE8}") = "(deps)", "..\deps", "{01DF18E8-89C6-A25E-0006-40F7C4BCED1B}"

EndProject

Project("{2150E333-8FDC-42A3-9474-1A3956D46DE8}") = "(deps)", "..\deps\libwebrtc\deps", "{D966A658-BE1C-1BD2-0722-2600B9349A98}"

EndProject

Project("{2150E333-8FDC-42A3-9474-1A3956D46DE8}") = "(libwebrtc)", "..\deps\libwebrtc", "{FB0A5069-0053-EE13-E40C-60538EA8CE06}"

EndProject

Project("{8BC9CEB8-8B4A-11D0-8D11-00A0C91BC942}") = "abseil", "deps\libwebrtc\deps\abseil-cpp\abseil.vcxproj", "{DFA383C2-91FE-437B-0444-F2F33499DDC7}"

EndProject

Project("{8BC9CEB8-8B4A-11D0-8D11-00A0C91BC942}") = "getopt", "deps\getopt\getopt.vcxproj", "{AFEE2A84-DB2D-27F1-3043-9B3D865A4D15}"

EndProject

Project("{8BC9CEB8-8B4A-11D0-8D11-00A0C91BC942}") = "libsrtp", "deps\libsrtp\libsrtp.vcxproj", "{71857B09-AE0C-B657-4F6C-7F3D2691CB08}"

EndProject

Project("{8BC9CEB8-8B4A-11D0-8D11-00A0C91BC942}") = "libuv", "deps\libuv\libuv.vcxproj", "{67F13F84-49C0-7EF1-8D5F-36FF35C96EE7}"

EndProject

Project("{8BC9CEB8-8B4A-11D0-8D11-00A0C91BC942}") = "libwebrtc", "deps\libwebrtc\libwebrtc.vcxproj", "{DB50CC5B-4AE9-39BA-CB9F-D8A17BE408F6}"

EndProject

Project("{8BC9CEB8-8B4A-11D0-8D11-00A0C91BC942}") = "mediasoup-worker", "mediasoup-worker.vcxproj", "{029A5B23-74C5-9996-4D17-1993FE1EEF6B}"

	ProjectSection(ProjectDependencies) = postProject

		{7DBBD927-E185-EC22-DF1B-E7DDF46ADA7D} = {7DBBD927-E185-EC22-DF1B-E7DDF46ADA7D}

		{67F13F84-49C0-7EF1-8D5F-36FF35C96EE7} = {67F13F84-49C0-7EF1-8D5F-36FF35C96EE7}

		{3C9080F6-424E-756E-3B96-07AB835D5371} = {3C9080F6-424E-756E-3B96-07AB835D5371}

		{71857B09-AE0C-B657-4F6C-7F3D2691CB08} = {71857B09-AE0C-B657-4F6C-7F3D2691CB08}

		{2C07BFDE-1F7B-83FE-C4CF-B8AFB8CD3554} = {2C07BFDE-1F7B-83FE-C4CF-B8AFB8CD3554}

		{DB50CC5B-4AE9-39BA-CB9F-D8A17BE408F6} = {DB50CC5B-4AE9-39BA-CB9F-D8A17BE408F6}

		{DFA383C2-91FE-437B-0444-F2F33499DDC7} = {DFA383C2-91FE-437B-0444-F2F33499DDC7}

		{AFEE2A84-DB2D-27F1-3043-9B3D865A4D15} = {AFEE2A84-DB2D-27F1-3043-9B3D865A4D15}

	EndProjectSection

EndProject

Project("{8BC9CEB8-8B4A-11D0-8D11-00A0C91BC942}") = "netstring", "deps\netstring\netstring.vcxproj", "{7DBBD927-E185-EC22-DF1B-E7DDF46ADA7D}"

EndProject

Project("{8BC9CEB8-8B4A-11D0-8D11-00A0C91BC942}") = "openssl", "deps\openssl\openssl.vcxproj", "{3C9080F6-424E-756E-3B96-07AB835D5371}"

EndProject

Project("{8BC9CEB8-8B4A-11D0-8D11-00A0C91BC942}") = "usrsctp", "deps\usrsctp\usrsctp.vcxproj", "{2C07BFDE-1F7B-83FE-C4CF-B8AFB8CD3554}"

EndProject

Global

	GlobalSection(SolutionConfigurationPlatforms) = preSolution

		Release|Win32 = Release|Win32

		Debug|Win32 = Debug|Win32

	EndGlobalSection

	GlobalSection(ProjectConfigurationPlatforms) = postSolution

		{029A5B23-74C5-9996-4D17-1993FE1EEF6B}.Release|Win32.ActiveCfg = Release|Win32

		{029A5B23-74C5-9996-4D17-1993FE1EEF6B}.Release|Win32.Build.0 = Release|Win32

		{029A5B23-74C5-9996-4D17-1993FE1EEF6B}.Debug|Win32.ActiveCfg = Debug|Win32

		{029A5B23-74C5-9996-4D17-1993FE1EEF6B}.Debug|Win32.Build.0 = Debug|Win32

		{2C07BFDE-1F7B-83FE-C4CF-B8AFB8CD3554}.Release|Win32.ActiveCfg = Release|Win32

		{2C07BFDE-1F7B-83FE-C4CF-B8AFB8CD3554}.Release|Win32.Build.0 = Release|Win32

		{2C07BFDE-1F7B-83FE-C4CF-B8AFB8CD3554}.Debug|Win32.ActiveCfg = Debug|Win32

		{2C07BFDE-1F7B-83FE-C4CF-B8AFB8CD3554}.Debug|Win32.Build.0 = Debug|Win32

		{3C9080F6-424E-756E-3B96-07AB835D5371}.Release|Win32.ActiveCfg = Release|Win32

		{3C9080F6-424E-756E-3B96-07AB835D5371}.Release|Win32.Build.0 = Release|Win32

		{3C9080F6-424E-756E-3B96-07AB835D5371}.Debug|Win32.ActiveCfg = Debug|Win32

		{3C9080F6-424E-756E-3B96-07AB835D5371}.Debug|Win32.Build.0 = Debug|Win32

		{67F13F84-49C0-7EF1-8D5F-36FF35C96EE7}.Release|Win32.ActiveCfg = Release|Win32

		{67F13F84-49C0-7EF1-8D5F-36FF35C96EE7}.Release|Win32.Build.0 = Release|Win32

		{67F13F84-49C0-7EF1-8D5F-36FF35C96EE7}.Debug|Win32.ActiveCfg = Debug|Win32

		{67F13F84-49C0-7EF1-8D5F-36FF35C96EE7}.Debug|Win32.Build.0 = Debug|Win32

		{71857B09-AE0C-B657-4F6C-7F3D2691CB08}.Release|Win32.ActiveCfg = Release|Win32

		{71857B09-AE0C-B657-4F6C-7F3D2691CB08}.Release|Win32.Build.0 = Release|Win32

		{71857B09-AE0C-B657-4F6C-7F3D2691CB08}.Debug|Win32.ActiveCfg = Debug|Win32

		{71857B09-AE0C-B657-4F6C-7F3D2691CB08}.Debug|Win32.Build.0 = Debug|Win32

		{7DBBD927-E185-EC22-DF1B-E7DDF46ADA7D}.Release|Win32.ActiveCfg = Release|Win32

		{7DBBD927-E185-EC22-DF1B-E7DDF46ADA7D}.Release|Win32.Build.0 = Release|Win32

		{7DBBD927-E185-EC22-DF1B-E7DDF46ADA7D}.Debug|Win32.ActiveCfg = Debug|Win32

		{7DBBD927-E185-EC22-DF1B-E7DDF46ADA7D}.Debug|Win32.Build.0 = Debug|Win32

		{AFEE2A84-DB2D-27F1-3043-9B3D865A4D15}.Release|Win32.ActiveCfg = Release|Win32

		{AFEE2A84-DB2D-27F1-3043-9B3D865A4D15}.Release|Win32.Build.0 = Release|Win32

		{AFEE2A84-DB2D-27F1-3043-9B3D865A4D15}.Debug|Win32.ActiveCfg = Debug|Win32

		{AFEE2A84-DB2D-27F1-3043-9B3D865A4D15}.Debug|Win32.Build.0 = Debug|Win32

		{DB50CC5B-4AE9-39BA-CB9F-D8A17BE408F6}.Release|Win32.ActiveCfg = Release|Win32

		{DB50CC5B-4AE9-39BA-CB9F-D8A17BE408F6}.Release|Win32.Build.0 = Release|Win32

		{DB50CC5B-4AE9-39BA-CB9F-D8A17BE408F6}.Debug|Win32.ActiveCfg = Debug|Win32

		{DB50CC5B-4AE9-39BA-CB9F-D8A17BE408F6}.Debug|Win32.Build.0 = Debug|Win32

		{DFA383C2-91FE-437B-0444-F2F33499DDC7}.Release|Win32.ActiveCfg = Release|Win32

		{DFA383C2-91FE-437B-0444-F2F33499DDC7}.Release|Win32.Build.0 = Release|Win32

		{DFA383C2-91FE-437B-0444-F2F33499DDC7}.Debug|Win32.ActiveCfg = Debug|Win32

		{DFA383C2-91FE-437B-0444-F2F33499DDC7}.Debug|Win32.Build.0 = Debug|Win32

	EndGlobalSection

	GlobalSection(SolutionProperties) = preSolution

		HideSolutionNode = FALSE

	EndGlobalSection

	GlobalSection(NestedProjects) = preSolution

		{DFA383C2-91FE-437B-0444-F2F33499DDC7} = {9DC36AD0-A741-FFB2-D815-5B81F7BAF592}

		{FB0A5069-0053-EE13-E40C-60538EA8CE06} = {01DF18E8-89C6-A25E-0006-40F7C4BCED1B}

		{AFEE2A84-DB2D-27F1-3043-9B3D865A4D15} = {01DF18E8-89C6-A25E-0006-40F7C4BCED1B}

		{71857B09-AE0C-B657-4F6C-7F3D2691CB08} = {01DF18E8-89C6-A25E-0006-40F7C4BCED1B}

		{67F13F84-49C0-7EF1-8D5F-36FF35C96EE7} = {01DF18E8-89C6-A25E-0006-40F7C4BCED1B}

		{7DBBD927-E185-EC22-DF1B-E7DDF46ADA7D} = {01DF18E8-89C6-A25E-0006-40F7C4BCED1B}

		{3C9080F6-424E-756E-3B96-07AB835D5371} = {01DF18E8-89C6-A25E-0006-40F7C4BCED1B}

		{2C07BFDE-1F7B-83FE-C4CF-B8AFB8CD3554} = {01DF18E8-89C6-A25E-0006-40F7C4BCED1B}

		{9DC36AD0-A741-FFB2-D815-5B81F7BAF592} = {D966A658-BE1C-1BD2-0722-2600B9349A98}

		{D966A658-BE1C-1BD2-0722-2600B9349A98} = {FB0A5069-0053-EE13-E40C-60538EA8CE06}

		{DB50CC5B-4AE9-39BA-CB9F-D8A17BE408F6} = {FB0A5069-0053-EE13-E40C-60538EA8CE06}

	EndGlobalSection

EndGlobal

**Comment by ibc** [comment] 2019-11-18 17:06
@haiyangwu can you help here, please?

**Comment by haiyangwu** [comment] 2019-11-19 01:28
@ibc I'll handle this. @EyalSi According to [this](https://stackoverflow.com/a/37598456/2085408), It seems the project is missing and out the link of `mediasoup-worker.sln`, please use Visual Studio to open the `mediasoup-worker.sln` and take a quick check.

**Comment by EyalSi** [comment] 2019-11-19 11:03
@haiyangwu THANKS for the help. it seems like a different error/problem. looked at the sln file, but it looks ok (to me...) and even builds fine in visual studio - not sure how to continue from here.

**Comment by haiyangwu** [comment] 2019-11-19 18:13
Confirmed, it's a bug. But I haven't found the exact reason and it broke from which commit. I'll follow and fix this bug.

@EyalSi you can merge my [quick-fix-commit](https://github.com/haiyangwu/mediasoup/commit/86b09a8112b5fc3e50dc5ba5a9bdf96d7cabecac) to continue.

> This commit use `devenv` instead of `MSBuild`. And of cource, add the `devenv` path to the Windows PATH environment variable (e.g. `C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\`)
>
> Ref [microsoft devenv-command-line-switches](https://docs.microsoft.com/en-us/visualstudio/ide/reference/devenv-command-line-switches?view=vs-2019)

**Comment by haiyangwu** [comment] 2019-11-20 15:33
After dozens of trials, Found that`Python3` will trigger this bug but `Python2` is ok.  I'll continue this task tomorrow.

@EyalSi would you please try to use `Python2` and verify on your environment.

**Comment by EyalSi** [comment] 2019-11-24 14:53
@haiyangwu THANKS! Yes, it is working with python2 on windows!

**Comment by ibc** [comment] 2019-11-24 14:54
So, is this an issue in gyp or where?

**Comment by haiyangwu** [comment] 2019-11-24 17:28
> So, is this an issue in gyp or where?

It's just in gyp. [A fix commit](https://github.com/haiyangwu/mediasoup/commit/9ab0d62d9cf4726943452da0f1f9547c49d100ff) was just pushed to my forked repo.  But I'm not quite sure about it.

@ibc Cloud you please follow the clue blew and review for me? Does it make sense?

* From [the doc of IO in Python2](https://docs.python.org/2/library/io.html)
`newline controls how universal newlines works (it only applies to text mode).`

* From [the doc of IO in Python3](https://docs.python.org/3/library/io.html)
`newline controls how line endings are handled. It can be None, '', '\n', '\r', and '\r\n'. It works as follows`

In `deps\gyp\pylib\gyp\MSVSNew.py` line 255 ~ line 351, when invoking `f.write`, it all include` \r\n`.
In `deps\gyp\pylib\gyp\common.py` line 348, `self.tmp_file = os.fdopen(tmp_fd, 'w', newline='')`

The file was opened in Mode `w`, as 'Python2'  document described, it only applies to text mode,  it doesn't replace the newlines(` \r\n`), but  'Python3', all mode is included,  the ` \r\n` will be replaced and end up with ` \r\r\n` which leads to the bug above.

**Comment by ibc** [comment] 2019-11-24 20:47
Thanks. It makes sense. However I have no idea about Python. Did you send a PR or patch to GYP project? I want to avoid having a customized version of gyp in mediasoup (I want to be able to update `gyp` at any time without having to apply local patches):

https://bugs.chromium.org/p/gyp/issues/list

**Comment by haiyangwu** [comment] 2019-11-26 01:42
@ibc  I'll send a PR or patch and update a brief here when done.

**Comment by ibc** [comment] 2019-11-26 09:18
Thanks.

**Comment by haiyangwu** [comment] 2019-12-01 17:33
@ibc It has been a busy week. Just now, the [issue](https://bugs.chromium.org/p/gyp/issues/detail?id=556) with a patch was sent. 

For now,  [doc about installation on Windows](https://mediasoup.org/documentation/v3/mediasoup/installation/#windows) should change a bit.

```
* python version 2
```

**Comment by ibc** [comment] 2019-12-01 20:49
Thanks, doc updated and deployed.

Please @EyalSi, @jmillan, star the [issue](https://bugs.chromium.org/p/gyp/issues/detail?id=556) in Chromium GYP.

Let's keep this issue open until the issue in GYP is fixed.

**Comment by ibc** [comment] 2019-12-26 17:19
Hi guys, the GYP developers do not seem to be very active. Since you have a working patch, can you instead upload a CL to GYP? It's easy:

* https://gyp.gsrc.io/docs/Hacking.md

**Comment by ibc** [comment] 2020-02-13 07:29
Just decided to drop gyp and move to CMake. See #359.

**Comment by 7Hazard** [comment] 2021-03-17 16:07
So, this is still a thing when i try to npm mediasoup. I am trying to use vs2019 and python3 though so that might be the reason on my end.

**Comment by ibc** [comment] 2021-03-17 17:57
This is a thing because it's not fixed. We are gonna migrate to CMake (there is a separate issue about it already).

**Comment by nazar-pc** [comment] 2021-10-10 16:20
We moved away from GYP as a build system, so this particular issue should now be irrelevant, closing.

**Closed as completed by nazar-pc** 2021-10-10 16:20 UTC
Labels: help wanted, windows
