### ISSUE TITLE
Allow disabling signal handlers

### ISSUE THREAD

**Issue by nazar-pc** [versatica/mediasoup#405] opened 2020-05-16 17:22 UTC
## Feature Request
Looks like whenever SIGINT is sent to Node.js app, worker is stopped, even though its `.close()` method is not called explicitly.

This causes issues when there is a need to handle application shutdown gracefully, like to wait for certain things to happen until configured timeout.

I believe this is something within mediasoup even though I was not able to trace where it happens exactly yet.

Here is the log:
```
  mediasoup:Channel [pid:428706] RTC::DtlsTransport::OnSslInfo() | sending DTLS warning alert: close notify +1s
  mediasoup:Channel Consumer Channel ended by the worker process +0ms
  mediasoup:Channel Producer Channel ended by the worker process +1ms
  mediasoup:Worker close() +6s
  mediasoup:Channel close() +199ms
  mediasoup:Router workerClosed() +6s
  mediasoup:Transport routerClosed() +6s
  mediasoup:Transport close() +0ms
  mediasoup:Channel request() [method:transport.close, id:7] +1ms
  mediasoup:Producer transportClosed() +6s
  mediasoup:Producer transportClosed() +0ms
  mediasoup:ERROR:Worker worker process died unexpectedly [pid:428706, code:0, signal:null] +0ms
```

**Comment by ibc** [comment] 2020-05-17 09:19
I can guarantee you that this SIGING handler is working properly and we use graceful shutdown in comercial applications for long time. Such a SIGINT handler does not avoid it at all. So this is not a bug (so let me close this issue report because I don't want to keep discussions in GitHub and want to keep the issue list clean).

If you want to do graceful shutdown, you have to add a signal handler in your Node app (for a specific signal, I usually use SIGUSR2) and do your own stuff such as keeping such a flag and calling `worker.close()` once the last alive `Router` in that `Worker` is closed.

**Closed as completed by ibc** 2020-05-17 09:19 UTC
Labels: feature

**Comment by nazar-pc** [comment] 2020-05-17 09:26
Are you saying that there is indeed SIGINT handler that stops worker and that is expected and should not be disabled?
If so then it is very frustrating and should be configurable at least.
Standard signal for stopping an app is either SIGINT or SIGTERM. Re-mapping it to something like SIGUSR2 is ugly and shouldn't be required by application (remember, mediasoup is just a library). This is the first time I see library handling signals that is not possible to disable.

**Comment by ibc** [comment] 2020-05-17 09:33
> Are you saying that there is indeed SIGINT handler that stops worker and that is expected and should not be disabled?

No, I did not say that.

The default behavior of libuv (or any C/C++ app) upon receipt of SIGINT or SIGTERM is just exit. In mediasoup-worker we do the **same**, however, instead of just exiting the `mediasoup-worker` process, we gracefully close it by calling `this->Close()` method. Just check `Worker.cpp` code, please.

> Re-mapping it to something like SIGUSR2 is ugly and shouldn't be required by application

That's not what I said. I meant that **at Node application level** when my mediasoup based app receives a SIGUSR2 signal checks whether there are alive `Routers` and, if not, it terminates the Node app. Otherwise it sets a flag somewhere and, once the latest alive `Router` ends, it terminates the Node app. That's application level graceful termination and that's the only I meant. And this is done at application level. Zero relationship with mediasoup library.

**Comment by ibc** [comment] 2020-05-17 09:36
> instead of just exiting the `mediasoup-worker` process, we gracefully close it by calling `this->Close()` method

To clarify: this means that, when the Node app calls `worker.close()`, or when the Node app sends a SIGINT/SIGTERM signal to a `mediasoup-worker` process, or when the Node app is just terminated, the `mediasoup-worker` process runs `Worker::Close()` which gracefully terminates the libuv loop by properly closing all active handlers (UDP/TCP sockets, timers, etc). This gives us a chance to properly send DTLS Close Alert messages, etc. This is just fine and does not break any expected behavior.

**Comment by nazar-pc** [comment] 2020-05-17 10:21
Hm... my observation is that worker stops before my app calls `worker.close()`.

I have a signal handlers for SIGINT and SIGTERM, but while I'm waiting for clients to disconnect worker already exits for some reason. Maybe Node.js signals are forwarded to child processes automatically? Then this feature request is about disabling that behavior.

**Comment by ibc** [comment] 2020-05-17 10:54
If you set a SIGINT handler into your Node app and, for example, ignore the signal, mediasoup-worker should not be closed at all. I've confirmed it as follows:

```js
process.on('SIGINT', () => {
  console.warn('-------- SIGINT received --------');

  // do nothing else  
});
```

If you then send `kill -s SIGINT NODE_PROCESS_PID` absolutely nothing happens and mediasoup-worker processes remain alive.

**Comment by nazar-pc** [comment] 2020-05-17 10:59
Interesting, with `kill -s INT` it is actually the case, but not with `ctrl+c` for some reason. Tried `dash` and `fish` shells. It should be sending `SIGINT` and I have never experienced anything like this before.

**Comment by ibc** [comment] 2020-05-17 11:59
At some point this should be an issue elsewhere (for instance in the specific terminal) rather than in mediasoup. mediasoup does not do any custom handling for SIGINT other than graceful exit in `mediasoup-worker` process.

When the Node app exits, its `UnixSocket` reliable sockets with `mediasoup-worker` processes are closed. That's detected by `mediasoup-worker` processes and gracefully close the process (same as if `SIGINT` or `SIGTERM` were received):

```c++
inline void Worker::OnChannelClosed(Channel::UnixStreamSocket* /*socket*/)
{
	MS_TRACE_STD();

	// If the pipe is remotely closed it may mean that mediasoup Node process
	// abruptly died (SIGKILL?) so we must die.
	MS_ERROR_STD("channel remotely closed, closing myself");

	Close();
}
```
