### ISSUE TITLE
Dropped RTP packets from rtpStreamer

### ISSUE THREAD

**Issue by dansnerd** [versatica/mediasoup#285] opened 2019-03-27 20:24 UTC
## Bug Report

**IMPORTANT:** Do NOT open an issue here if you have problems or questions regarding mediasoup. Use the mediasoup public mailing list instead:
> 
> https://groups.google.com/forum/#!forum/mediasoup

### Your environment

- Operating system: Debian 8
- Node version: 10.15.3
- npm version: 6.4.1
- gcc/clang version: 4.9.2
- mediasoup version: 2.6.10
- mediasoup-client version: 2.4.9
- codecs: h264 + opus

### Issue description

We're using mediasoup as a webrtc ingest into legacy systems in the following configuration:
browser --(tcp)--> mediasoup --> rtpStreamer --> ffmpeg --> existing systems (hls, etc)

Each broadcaster is alone in a new room (10 broadcasters = 10 rooms, 1 peer in each).  As soon as the producers are added, we spawn ffmpeg (locally), with the following params:
 -analyzeduration 30M -probesize 30M -max_delay 1000000 -hide_banner -nostdin -y -protocol_whitelist udp,rtp,pipe -c:a libopus -i - -c:v copy -c:a aac -ar 44100 -ab 48k -ac 2 -f flv rtmp://xxxxx
(along with a few other transcodes)

And pipe in an SDP of:
v=0
o=- 0 0 IN IP4 127.0.0.1
s=MS
c=IN IP4 127.0.0.1
t=0 0
m=audio ' + audioPort + ' RTP/AVP 100
a=recvonly
a=rtpmap:100 opus/48000/2
a=fmtp:100 minptime=10;useinbandfec=1
m=video ' + videoPort + ' RTP/AVP 101
a=recvonly
a=rtpmap:101 H264/90000
a=fmtp:101 packetization-mode=1

This works properly, and the stream is transcoded and sent out via RTMP to our existing infrastructure.

Every so often, we see a hiccup, where every ffmpeg stream reports signficant packet loss, with every stream spamming (with differing counts):
stream1: [sdp @ 0x695b040] max delay reached. need to consume packet
stream1: [sdp @ 0x695b040] RTP: missed 265 packets
stream50: [sdp @ 0x695b040] max delay reached. need to consume packet
stream50: [sdp @ 0x5819040] RTP: missed 253 packets
stream32: [sdp @ 0x695b040] max delay reached. need to consume packet
stream32: [sdp @ 0x6985040] RTP: missed 21 packets
etc

All of the streams end up poor quality until the next keyframe arrives, and the issue resolves.  Server load is low when the issue happens (25% cpu usage, etc), and streams are from different geo locations (multiple countries), so unlikely to be a geo-localized problem.

We're investigating if it could be incoming network/kernel issues, but don't see anything obvious there.  Is there any way to debug this and see if the errors/dropped-packets are coming from ingest into mediasoup, within mediasoup, or mediasoup being delayed in relaying RTP?

**Comment by ibc** [comment] 2019-03-27 20:47
I'm not an expert in ffmpeg or GStreamer but AFAIK unfortunately ffmpeg does not use any kind of RTP jitter buffer. In the video sender has some packet lost mediasoup will request RTP packet retransmission to it. This usually solves the problem in receivers (assuming they do jitter buffer). Otherwise this means that the SFU will forward packets to ffmpeg with the following RTP seq numbers:

1000, 1001, 1005, 1006, 1007, 1002, 1003, 1004

and ffmpeg won't be able to properly decode them because they do not arrive in order. This is not a bug in mediasoup since it's a SFU and, thus, it's not supposed to be a RTP "consumer" but a RTP "forwarder". Receiving peers are responsible of implementing RTP jitter buffer to properly consume packets that do not arrive in order.

The solution? You must implement your own buffer or use something like [rtpjitterbuffer](https://gstreamer.freedesktop.org/data/doc/gstreamer/head/gst-plugins-good/html/gst-plugins-good-plugins-rtpjitterbuffer.html) in gstreamer:

> _"This element reorders and removes duplicate RTP packets as they are received from a network source. [...]  The rtpjitterbuffer will wait for missing packets up to a configurable time limit using the “latency” property. Packets arriving too late are considered to be lost packets."_

I'll close this issue since it's not a real issue in mediasoup but a limitation in ffmpeg RTP imlpementation (which lacks this one and many others). AFAIK GStreamer is MUCH more suitable for consuming a RTP stream.

> We're investigating if it could be incoming network/kernel issues, but don't see anything obvious there. Is there any way to debug this and see if the errors/dropped-packets are coming from ingest into mediasoup, within mediasoup, or mediasoup being delayed in relaying RTP?

You can just check packet lost and packet repaired in mediasoup RTP stats (those associated to the video Producer), or check the stats in the video sender itself (if Chrome you can check it in `chrome://webtc-internals`).

**Closed by ibc** 2019-03-27 20:47 UTC
Labels: bug

**Comment by dansnerd** [comment] 2019-03-27 20:51
Unfortunately, all of the streamers we've checked report 0 packet loss during these issues (checking graphs in chrome://webrtc-internals).  We're confident that the original stream into mediastreamer is not dropping packets.  I'll check into the stats on the mediasoup side.

**Comment by ibc** [comment] 2019-03-27 20:56
Even if there is no packet loss there could be packet disorder, and that would affect ffmpeg the same way.

I mean:

1. If there is packet lost then there will be packet retransmission as well.
1. If there is no packet lost there could be packet disorder anyway.

In both cases ffmpeg will receive a non continuous RTP stream and will fail to decode video.

The way to verify if this is the problem may be easy:

* Just connect a Chrome as viewer (in some location with very good Internet connection to the SFU).
* Send video from a remote one.
* If you get frozen video in ffmpeg and not in the Chrome viewer, then that confirms the scenario above.

**Comment by dansnerd** [comment] 2019-03-27 21:06
First off, really appreciate your help in dealing with this, and your responsiveness :)

One thing we've now reproduced which leads me to believe the issue is outside of mediasoup, is we've tried running 2 instances of mediasoup on different sets of ports (same box), and see the issue present across both instances at the same time.  Suggests an issue of either resource contention or inbound networking to me.

The only reason I don't see the dropped packet/retransmit being the culprit is because we're seeing the issue present on 10+ different incoming streams at the exact same time.  For a single stream, we see that plenty of times (dropped packets, etc), and thats completely expected, but seeing it at the exact same time for every incoming stream on the box makes me think its not related to the individual incoming stream but something server-side.

I'll setup more tests (getStats, webrtc viewer) and see if we can narrow it down on our side.  Thanks again.

**Comment by ibc** [comment] 2019-03-27 21:27
Again, not an expert in ffmpeg, but assuming those ffmpeg processes are decoding video (in same host as mediasoup or other?) maybe the decoding is consuming lot of CPU producing UDP packet drops and so on?

Also let me insist on the fact that, even if there is no packet lost there may be unordered packets and that would affect ffmpeg the same way as if there was packet lost + retransmissions.

**Comment by dansnerd** [comment] 2019-03-27 21:33
We've tried ffmpeg both locally, and on external boxes.  As for unordered, I understand, but I don't see how we'd have unordered packets happening on every incoming stream at the exact same time (outside of something like network card problems, kernel tuning, etc).  Working on getting stats data during the events :)

**Comment by jmillan** [comment] 2019-03-29 09:52
@dansnerd,

What about the CPU usage on the ffmpeg side? Maybe it has no enough resources to consume all the input data. I would suggest trying faster muti-core CPU host to see if there are differences.

Another approach to test this theory would be generating less RTP in the source so ffmpeg has less RTP packets to process.

**Comment by ibc** [comment] 2019-03-29 10:19
> @dansnerd,
> 
> What about the CPU usage on the ffmpeg side? Maybe it has no enough resources to consume all the input data. I would suggest trying faster muti-core CPU host to see if there are differences.

In addition to that (please confirm about it), you may want to provide ffmpeg with high networking capabilities. We are aware that, at least when it comes to **encode HD video** with ffmpeg, some Kernel tuning is required:

```
net.core.rmem_max=16777216
net.core.wmem_max=16777216
net.core.rmem_default=1048576
net.core.wmem_default=1048576
net.ipv4.udp_rmem_min=8192
net.ipv4.udp_wmem_min=8192
```

I expect the very same is needed for ffmpeg to properly decode. The fact that your problem happens in all ffmpeg instances at the same time (consuming different video sources) makes me strongly think that it must be due to pike CPU or network usage.

**Comment by dansnerd** [comment] 2019-03-29 13:28
> What about the CPU usage on the ffmpeg side? Maybe it has no enough resources to consume all the input data. I would suggest trying faster muti-core CPU host to see if there are differences.

We've tested both locally and on our (in production) remote transcoding cluster, which easily handles 50-60 streams per box, and we're seeing this issue consistently down near 7-10 streams.

> In addition to that (please confirm about it), you may want to provide ffmpeg with high networking capabilities. We are aware that, at least when it comes to encode HD video with ffmpeg, some Kernel tuning is required:

The issue is also happening with ffmpeg running on the same box as mediasoup, over localhost networking, I wouldn't think buffer sizes would matter there?

**Comment by ibc** [comment] 2019-03-29 13:43
Yes, UDP buffer sizes can affect even in localhost. If it takes too long for ffmpeg to decode a incoming video RTP stream, the kernel UDP buffer may collapse so some UDP datagrams may be lost and, hence, ffmpeg would not find them (and will report those losses).

**Comment by dansnerd** [comment] 2019-03-29 15:05
Understood, but that would require 10 different ffmpeg processes, listening on different sockets (with different buffers) to all pause in decoding very different streams at the exact same time, such that all 10 buffers filled at the same time.

We'll try to split the ffmpeg procs across multiple servers, and see if they still all hiccup at the same time.

**Comment by dansnerd** [comment] 2019-04-01 19:33
So we've now replicated the issue with 10 streams into mediasoup on one box, splitting to ffmpeg on two different boxes.  When the issue happens, we see both ffmpeg boxes spam about being starved for packets at the exact same time.  The only way I can see this happening is something in mediasoup locking up and not sending out RTP, starving both the ffmpeg boxes at the same time?
