### ISSUE TITLE
std:bad_alloc Error

### ISSUE THREAD

**Issue by tazmanyak** [versatica/mediasoup#528] opened 2021-03-11 13:31 UTC
Hello,

I’m getting this error after one hour or so time passed in the system. When there are more than 50 consumers and about 20 producers in the system server.js throws this exception and terminated.

![image](https://user-images.githubusercontent.com/1527013/110794239-96abc480-8286-11eb-8b80-d14cfe55ca5d.png)

From the beginning, I was getting **heap out of memory error** and I fixed by setting --max-old-space-size. After that I got another error which is "S**cavenger: semi space copy Allocation Failed, Heap Out of memory error"**. Then I set --max-semi-space-size. Both error fixed but I got another error of "**str::bad_alloc**". I researched more than 3-4 days and i could not manage to solve this.

If you can help me to solve this problem, I will be very happy.

Thanks in advance

**Comment by ibc** [comment] 2021-03-11 14:26
If it was a bug in mediasoup C++ code, you'd get a [coredump](https://mediasoup.org/support/#crashes-in-mediasoup-get-a-core-dump) and a different error log referencing the mediasoup-worker process.

As the log above clearly says, the SIGABRT is happening in the **Node** process itself, probably in the native C code of a Node dependency (`socket.io` in your case, or in a subdependency of it). Not a bug in mediasoup. Closing.

**Closed as completed by ibc** 2021-03-11 14:26 UTC
