### ISSUE TITLE
Evaluate RtpDataCounter with 3 seconds instead of just 1

### ISSUE THREAD

**Issue by ibc** [versatica/mediasoup#312] opened 2019-06-14 08:59 UTC
We no longer use the `rtpStreamRecv->GetBitrate()` to detect simulcast stream inactivity (but a timer) so we don't need to limit the `RtpDataCounter` to 1 second window-size.

We may get better results (specially in VP9 SVC in which the Chrome per-layer bitrate oscillates so crazy) with a higher window size, i.e. 3 seconds.

**Comment by ibc** [comment] 2019-06-26 06:41
In order to test it, just open the online demo (or do it locally with latest versions) as follows:

https://v3demo.mediasoup.org/?roomId=FOOBAR&info=true&handler=Chrome67

It will use Chrome67 handler which, somehow, does enable simulcast for VP8 screen sharing and uses 1 temporal layer in spatial layer 0 and 2 temporal layers in spatial layer 1. The demo app now sets `dtx:true` in all `encodings` when doing screen sharing, so the RTP inactivity timer does not run at all. So this is a good chance to share a small white screen and see if the consumer receives "layers -1" due to `GetBitrate()` returning 0.

**Comment by ibc** [comment] 2019-07-16 15:39
I'm doing some tests with `RateCalculator rate{ /*windowSize*/ 2500 };` (instead of the default 1000 value) and it works fine. However I've never been able to reproduce the **problem**. Let me clarify what the problem is:

* Screen sharing with vp8 simulcast (`&handler=Chrome67` is required in the demo app as explained above).
* A viewer tab.
* There is no "RTP inactivity checks" since the demo app enables DTX when screen sharing.
* Wait until the viewer gets `spatial layer -1` due to lack of RTP during 1 second (this will happen if the sender does not send RTP during 1 second and the Consumer checks `producerRtpStream->GetBitrate()` and gets 0, so it disables that stream and notifies layer -1).

@jmillan does it make sense?

**Comment by jmillan** [comment] 2019-07-16 15:56
And were you able to reproduce the problem it with default window size value (1000ms)?

**Comment by ibc** [comment] 2019-07-16 15:57
No. Never. You did. No idea why or how you test it. But never seen that problem here.

**Comment by jmillan** [comment] 2019-07-16 15:59
I recall that the problem was fixed by enabling DTX.

**Comment by ibc** [comment] 2019-07-16 16:00
no no, you reproduced it after DTX. Sure. DTX just disables the "RTP inactivity check" (that we do not want on screen sharing).

**Comment by ibc** [comment] 2019-07-16 19:19
ok, confirmed that this happens with VP8 screen sharing with simulcast when sharing a static Chrome tab. I've added some logs to check how long the lack of RTP takes:

```
RTC::Producer::ReceiveRtpPacket() | packet [now:1120466128, ssrc:669693351, temporalLayer:0]
RTC::Producer::ReceiveRtpPacket() | packet [now:1120466140, ssrc:669693351, temporalLayer:0]
RTC::Producer::ReceiveRtpPacket() | packet [now:1120466158, ssrc:669693351, temporalLayer:0]

[no RTP]

RTC::Producer::ReceiveRtpPacket() | packet [now:1120467128, ssrc:669693351, temporalLayer:0]
RTC::Producer::ReceiveRtpPacket() | packet [now:1120467140, ssrc:669693351, temporalLayer:0]
RTC::Producer::ReceiveRtpPacket() | packet [now:1120467159, ssrc:669693351, temporalLayer:0]
RTC::Producer::ReceiveRtpPacket() | packet [now:1120467177, ssrc:669693351, temporalLayer:0]
```

So this is 1120467128 - 1120466158 = 970, so ~1 second, right?

If so it makes sense that with `windowSize = 1000` it "fails".

**Comment by ibc** [comment] 2019-07-16 19:23
And confirmed that it does not happen if `windowSize = 2500`.

@jmillan any other consideration for this change coming to your mind?

**Comment by jmillan** [comment] 2019-07-16 19:35
No, apart from the possible minimal CPU increase in `RateCalculator` due to the window size increase. I think we can obviate that.

Would then this value get increased for `SimulcastConsumer` and `SvcConsumer`?

**Comment by ibc** [comment] 2019-07-16 19:39
> Would then this value get increased for SimulcastConsumer and SvcConsumer?

The constructor of `RtpDataCounter` does not even allow passing any value for its internal `RateCalculator` instance and, if so, such a `RateCalculator` instance should be allocated dynamically (pointer).

Anyway, we must be consistent. If we calculate bitrate based on a 2500ms window for one type of consumer the same should apply to any other IMHO.

**Comment by ibc** [comment] 2019-07-16 19:41
NOTE: I've been told that other SFUs use a window size of 2 or 3 seconds.

**Comment by ibc** [comment] 2019-07-17 07:44
BTW the only thing I've changed is the this:

```diff
--- a/worker/include/RTC/RateCalculator.hpp
+++ b/worker/include/RTC/RateCalculator.hpp
@@ -12,11 +12,11 @@ namespace RTC
 	class RateCalculator
 	{
@@ -89,7 +89,7 @@ namespace RTC
 		size_t GetBytes() const;
 
 	private:
-		RateCalculator rate;
+		RateCalculator rate{ /*windowSize*/ 2500 };
 		size_t packets{ 0 };
 	};
```

**Comment by ibc** [comment] 2019-07-17 08:03
NOTE: We are mixing two different concepts here, that may be spliited into two different APIs (or not):

1. A way to calculate a stream bitrate, which obviously needs a "window" of `X` ms.
2. A way to know whether there have been RTP packets in the latest `Y` ms in a specific stream.

Right now we just use `stream->GetBitrate()` to check both, bitrate and RTP, so both `X` and `Y` are the same. However we could split them by adding a new `stream->GetLastRtpPacketAt()` API that returns the number of ms since the last RTP packet received in that stream (it would be a simple `this->lastRtpPacketAt` member in the `RtpStream` class updated for every handled RTP packet).

Not sure if required since, at the end, using 2-3 seconds for the bitrate window is a good value (also used by other SFUs) and 2-3 seconds is also a good limit to avoid the issue described above (lack of RTP during more than 1 second when doing screen sharing with simulcast).

**Comment by jmillan** [comment] 2019-07-17 13:15
I'm perfectly fine with 2-3 seconds window for the bitrate calculation, definitely

**Comment by ibc** [comment] 2019-07-17 13:16
Ok, will commit it then.

**Closed as completed** 2019-07-17 13:25 UTC
Labels: feature
