### ISSUE TITLE
SIGSEGV/SIGABRT worker 

### ISSUE THREAD

**Issue by artushin** [versatica/mediasoup#200] opened 2018-04-21 17:22 UTC
Finally got some good logs on the dying workers. Please excuse the lack of DEBUG formatting, I had to override console.log formatting with my own to make mediasoup logs work with my monitoring scheme.

```
Apr 21 01:26:15 privcalls-dev-privcalls-app-0-5-0-j75g sfu[438]: {"level":"info","time":"2018-04-21T01:26:15Z","message":"2018-04-21T01:26:15.820Z mediasoup:Producer \"producer.getStats\" request succeeded"}
Apr 21 01:26:16 privcalls-dev-privcalls-app-0-5-0-j75g sfu[438]: {"level":"info","time":"2018-04-21T01:26:16Z","message":"2018-04-21T01:26:16.656Z mediasoup:Consumer getStats()"}
Apr 21 01:26:16 privcalls-dev-privcalls-app-0-5-0-j75g sfu[438]: {"level":"info","time":"2018-04-21T01:26:16Z","message":"2018-04-21T01:26:16.657Z mediasoup:Channel request() [method:%s, id:%s]","data":["consumer.getStats",41784443]}
Apr 21 01:26:16 privcalls-dev-privcalls-app-0-5-0-j75g sfu[438]: {"level":"info","time":"2018-04-21T01:26:16Z","message":"2018-04-21T01:26:16.657Z mediasoup:Producer getStats()"}
Apr 21 01:26:16 privcalls-dev-privcalls-app-0-5-0-j75g sfu[438]: {"level":"info","time":"2018-04-21T01:26:16Z","message":"2018-04-21T01:26:16.657Z mediasoup:Channel request() [method:%s, id:%s]","data":["producer.getStats",63401881]}
Apr 21 01:26:16 privcalls-dev-privcalls-app-0-5-0-j75g sfu[438]: {"level":"info","time":"2018-04-21T01:26:16Z","message":"2018-04-21T01:26:16.657Z mediasoup:Channel request succeeded [id:%s]","data":[41784443]}
Apr 21 01:26:16 privcalls-dev-privcalls-app-0-5-0-j75g sfu[438]: {"level":"info","time":"2018-04-21T01:26:16Z","message":"2018-04-21T01:26:16.658Z mediasoup:Channel request succeeded [id:%s]","data":[63401881]}
Apr 21 01:26:16 privcalls-dev-privcalls-app-0-5-0-j75g sfu[438]: {"level":"info","time":"2018-04-21T01:26:16Z","message":"2018-04-21T01:26:16.658Z mediasoup:Consumer \"consumer.getStats\" request succeeded"}
Apr 21 01:26:16 privcalls-dev-privcalls-app-0-5-0-j75g sfu[438]: {"level":"info","time":"2018-04-21T01:26:16Z","message":"2018-04-21T01:26:16.658Z mediasoup:Producer \"producer.getStats\" request succeeded"}
Apr 21 01:26:16 privcalls-dev-privcalls-app-0-5-0-j75g sfu[438]: {"level":"info","time":"2018-04-21T01:26:16Z","message":"2018-04-21T01:26:16.821Z mediasoup:Consumer getStats()"}
Apr 21 01:26:16 privcalls-dev-privcalls-app-0-5-0-j75g sfu[438]: {"level":"info","time":"2018-04-21T01:26:16Z","message":"2018-04-21T01:26:16.821Z mediasoup:Channel request() [method:%s, id:%s]","data":["consumer.getStats",18317925]}
Apr 21 01:26:16 privcalls-dev-privcalls-app-0-5-0-j75g sfu[438]: {"level":"info","time":"2018-04-21T01:26:16Z","message":"2018-04-21T01:26:16.821Z mediasoup:Producer getStats()"}
Apr 21 01:26:16 privcalls-dev-privcalls-app-0-5-0-j75g sfu[438]: {"level":"info","time":"2018-04-21T01:26:16Z","message":"2018-04-21T01:26:16.821Z mediasoup:Channel request() [method:%s, id:%s]","data":["producer.getStats",79327681]}
Apr 21 01:26:16 privcalls-dev-privcalls-app-0-5-0-j75g sfu[438]: {"level":"info","time":"2018-04-21T01:26:16Z","message":"2018-04-21T01:26:16.822Z mediasoup:Channel request succeeded [id:%s]","data":[18317925]}
Apr 21 01:26:16 privcalls-dev-privcalls-app-0-5-0-j75g sfu[438]: {"level":"info","time":"2018-04-21T01:26:16Z","message":"2018-04-21T01:26:16.822Z mediasoup:Channel request succeeded [id:%s]","data":[79327681]}
Apr 21 01:26:16 privcalls-dev-privcalls-app-0-5-0-j75g sfu[438]: {"level":"info","time":"2018-04-21T01:26:16Z","message":"2018-04-21T01:26:16.822Z mediasoup:Consumer \"consumer.getStats\" request succeeded"}
Apr 21 01:26:16 privcalls-dev-privcalls-app-0-5-0-j75g sfu[438]: {"level":"info","time":"2018-04-21T01:26:16Z","message":"2018-04-21T01:26:16.822Z mediasoup:Producer \"producer.getStats\" request succeeded"}
Apr 21 01:26:17 privcalls-dev-privcalls-app-0-5-0-j75g sfu[438]: {"level":"info","time":"2018-04-21T01:26:17Z","message":"2018-04-21T01:26:17.657Z mediasoup:Consumer getStats()"}
Apr 21 01:26:17 privcalls-dev-privcalls-app-0-5-0-j75g sfu[438]: {"level":"info","time":"2018-04-21T01:26:17Z","message":"2018-04-21T01:26:17.658Z mediasoup:Channel request() [method:%s, id:%s]","data":["consumer.getStats",95585783]}
Apr 21 01:26:17 privcalls-dev-privcalls-app-0-5-0-j75g sfu[438]: {"level":"info","time":"2018-04-21T01:26:17Z","message":"2018-04-21T01:26:17.658Z mediasoup:Producer getStats()"}
Apr 21 01:26:17 privcalls-dev-privcalls-app-0-5-0-j75g sfu[438]: {"level":"info","time":"2018-04-21T01:26:17Z","message":"2018-04-21T01:26:17.658Z mediasoup:Channel request() [method:%s, id:%s]","data":["producer.getStats",41469770]}
Apr 21 01:26:17 privcalls-dev-privcalls-app-0-5-0-j75g sfu[438]: {"level":"info","time":"2018-04-21T01:26:17Z","message":"2018-04-21T01:26:17.659Z mediasoup:Channel request succeeded [id:%s]","data":[95585783]}
Apr 21 01:26:17 privcalls-dev-privcalls-app-0-5-0-j75g sfu[438]: {"level":"info","time":"2018-04-21T01:26:17Z","message":"2018-04-21T01:26:17.659Z mediasoup:Channel request succeeded [id:%s]","data":[41469770]}
Apr 21 01:26:17 privcalls-dev-privcalls-app-0-5-0-j75g sfu[438]: {"level":"info","time":"2018-04-21T01:26:17Z","message":"2018-04-21T01:26:17.659Z mediasoup:Consumer \"consumer.getStats\" request succeeded"}
Apr 21 01:26:17 privcalls-dev-privcalls-app-0-5-0-j75g sfu[438]: {"level":"info","time":"2018-04-21T01:26:17Z","message":"2018-04-21T01:26:17.659Z mediasoup:Producer \"producer.getStats\" request succeeded"}
Apr 21 01:26:17 privcalls-dev-privcalls-app-0-5-0-j75g sfu[438]: {"level":"info","time":"2018-04-21T01:26:17Z","message":"2018-04-21T01:26:17.821Z mediasoup:Consumer getStats()"}
Apr 21 01:26:17 privcalls-dev-privcalls-app-0-5-0-j75g sfu[438]: {"level":"info","time":"2018-04-21T01:26:17Z","message":"2018-04-21T01:26:17.822Z mediasoup:Channel request() [method:%s, id:%s]","data":["consumer.getStats",43965100]}
Apr 21 01:26:17 privcalls-dev-privcalls-app-0-5-0-j75g sfu[438]: {"level":"info","time":"2018-04-21T01:26:17Z","message":"2018-04-21T01:26:17.822Z mediasoup:Producer getStats()"}
Apr 21 01:26:17 privcalls-dev-privcalls-app-0-5-0-j75g sfu[438]: {"level":"info","time":"2018-04-21T01:26:17Z","message":"2018-04-21T01:26:17.822Z mediasoup:Channel request() [method:%s, id:%s]","data":["producer.getStats",15753810]}
Apr 21 01:26:17 privcalls-dev-privcalls-app-0-5-0-j75g sfu[438]: {"level":"info","time":"2018-04-21T01:26:17Z","message":"2018-04-21T01:26:17.822Z mediasoup:Channel request succeeded [id:%s]","data":[43965100]}
Apr 21 01:26:17 privcalls-dev-privcalls-app-0-5-0-j75g sfu[438]: {"level":"info","time":"2018-04-21T01:26:17Z","message":"2018-04-21T01:26:17.822Z mediasoup:Channel request succeeded [id:%s]","data":[15753810]}
Apr 21 01:26:17 privcalls-dev-privcalls-app-0-5-0-j75g sfu[438]: {"level":"info","time":"2018-04-21T01:26:17Z","message":"2018-04-21T01:26:17.822Z mediasoup:Consumer \"consumer.getStats\" request succeeded"}
Apr 21 01:26:17 privcalls-dev-privcalls-app-0-5-0-j75g sfu[438]: {"level":"info","time":"2018-04-21T01:26:17Z","message":"2018-04-21T01:26:17.823Z mediasoup:Producer \"producer.getStats\" request succeeded"}
Apr 21 01:26:18 privcalls-dev-privcalls-app-0-5-0-j75g sfu[438]: {"level":"info","time":"2018-04-21T01:26:18Z","message":"2018-04-21T01:26:18.658Z mediasoup:Consumer getStats()"}
Apr 21 01:26:18 privcalls-dev-privcalls-app-0-5-0-j75g sfu[438]: {"level":"info","time":"2018-04-21T01:26:18Z","message":"2018-04-21T01:26:18.658Z mediasoup:Channel request() [method:%s, id:%s]","data":["consumer.getStats",92038166]}
Apr 21 01:26:18 privcalls-dev-privcalls-app-0-5-0-j75g sfu[438]: {"level":"info","time":"2018-04-21T01:26:18Z","message":"2018-04-21T01:26:18.659Z mediasoup:Producer getStats()"}
Apr 21 01:26:18 privcalls-dev-privcalls-app-0-5-0-j75g sfu[438]: {"level":"info","time":"2018-04-21T01:26:18Z","message":"2018-04-21T01:26:18.659Z mediasoup:Channel request() [method:%s, id:%s]","data":["producer.getStats",49868437]}
Apr 21 01:26:18 privcalls-dev-privcalls-app-0-5-0-j75g sfu[438]: {"level":"info","time":"2018-04-21T01:26:18Z","message":"2018-04-21T01:26:18.659Z mediasoup:Channel request succeeded [id:%s]","data":[92038166]}
Apr 21 01:26:18 privcalls-dev-privcalls-app-0-5-0-j75g sfu[438]: {"level":"info","time":"2018-04-21T01:26:18Z","message":"2018-04-21T01:26:18.659Z mediasoup:Consumer \"consumer.getStats\" request succeeded"}
Apr 21 01:26:18 privcalls-dev-privcalls-app-0-5-0-j75g sfu[438]: {"level":"info","time":"2018-04-21T01:26:18Z","message":"2018-04-21T01:26:18.659Z mediasoup:Channel request succeeded [id:%s]","data":[49868437]}
Apr 21 01:26:18 privcalls-dev-privcalls-app-0-5-0-j75g sfu[438]: {"level":"info","time":"2018-04-21T01:26:18Z","message":"2018-04-21T01:26:18.659Z mediasoup:Producer \"producer.getStats\" request succeeded"}
Apr 21 01:26:18 privcalls-dev-privcalls-app-0-5-0-j75g sfu[438]: {"level":"info","time":"2018-04-21T01:26:18Z","message":"2018-04-21T01:26:18.823Z mediasoup:Consumer getStats()"}
Apr 21 01:26:18 privcalls-dev-privcalls-app-0-5-0-j75g sfu[438]: {"level":"info","time":"2018-04-21T01:26:18Z","message":"2018-04-21T01:26:18.823Z mediasoup:Channel request() [method:%s, id:%s]","data":["consumer.getStats",95099062]}
Apr 21 01:26:18 privcalls-dev-privcalls-app-0-5-0-j75g sfu[438]: {"level":"info","time":"2018-04-21T01:26:18Z","message":"2018-04-21T01:26:18.823Z mediasoup:Producer getStats()"}
Apr 21 01:26:18 privcalls-dev-privcalls-app-0-5-0-j75g sfu[438]: {"level":"info","time":"2018-04-21T01:26:18Z","message":"2018-04-21T01:26:18.823Z mediasoup:Channel request() [method:%s, id:%s]","data":["producer.getStats",64642044]}
Apr 21 01:26:18 privcalls-dev-privcalls-app-0-5-0-j75g sfu[438]: {"level":"info","time":"2018-04-21T01:26:18Z","message":"2018-04-21T01:26:18.824Z mediasoup:Channel request succeeded [id:%s]","data":[95099062]}
Apr 21 01:26:18 privcalls-dev-privcalls-app-0-5-0-j75g sfu[438]: {"level":"info","time":"2018-04-21T01:26:18Z","message":"2018-04-21T01:26:18.824Z mediasoup:Channel request succeeded [id:%s]","data":[64642044]}
Apr 21 01:26:18 privcalls-dev-privcalls-app-0-5-0-j75g sfu[438]: {"level":"info","time":"2018-04-21T01:26:18Z","message":"2018-04-21T01:26:18.824Z mediasoup:Consumer \"consumer.getStats\" request succeeded"}
Apr 21 01:26:18 privcalls-dev-privcalls-app-0-5-0-j75g sfu[438]: {"level":"info","time":"2018-04-21T01:26:18Z","message":"2018-04-21T01:26:18.824Z mediasoup:Producer \"producer.getStats\" request succeeded"}
Apr 21 01:26:19 privcalls-dev-privcalls-app-0-5-0-j75g sfu[438]: {"level":"warn","time":"2018-04-21T01:26:19Z","message":"mediasoup-worker's stderr: *** Error in `/usr/local/privcalls/sfu/node_modules/mediasoup/worker/out/Release/mediasoup-worker': corrupted double-linked list: 0x0000000001bdbd60 ***"}
Apr 21 01:26:19 privcalls-dev-privcalls-app-0-5-0-j75g sfu[438]: {"level":"info","time":"2018-04-21T01:26:19Z","message":"2018-04-21T01:26:19.446Z mediasoup:Channel channel ended by the other side"}
Apr 21 01:26:19 privcalls-dev-privcalls-app-0-5-0-j75g sfu[438]: {"level":"warn","time":"2018-04-21T01:26:19Z","message":"2018-04-21T01:26:19.446Z mediasoup:ERROR:Worker child process exited [id:%s, code:%s, signal:%s]","data":["yoveohms#1","SIGABRT"]}
Apr 21 01:26:19 privcalls-dev-privcalls-app-0-5-0-j75g sfu[438]: {"level":"info","time":"2018-04-21T01:26:19Z","message":"2018-04-21T01:26:19.446Z mediasoup:Worker close()"}


--



Apr 21 03:26:37 privcalls-dev-privcalls-app-0-5-0-j75g sfu[438]: {"level":"info","time":"2018-04-21T03:26:37Z","message":"2018-04-21T03:26:37.334Z mediasoup:Channel request() [method:%s, id:%s]","data":["transport.close",49946889]}
Apr 21 03:26:37 privcalls-dev-privcalls-app-0-5-0-j75g sfu[438]: {"level":"info","time":"2018-04-21T03:26:37Z","message":"2018-04-21T03:26:37.335Z mediasoup:Consumer close()"}
Apr 21 03:26:37 privcalls-dev-privcalls-app-0-5-0-j75g sfu[438]: {"level":"info","time":"2018-04-21T03:26:37Z","message":"2018-04-21T03:26:37.336Z mediasoup:Channel request succeeded [id:%s]","data":[50586885]}
Apr 21 03:26:37 privcalls-dev-privcalls-app-0-5-0-j75g sfu[438]: {"level":"info","time":"2018-04-21T03:26:37Z","message":"2018-04-21T03:26:37.336Z mediasoup:Channel request succeeded [id:%s]","data":[88418691]}
Apr 21 03:26:37 privcalls-dev-privcalls-app-0-5-0-j75g sfu[438]: {"level":"info","time":"2018-04-21T03:26:37Z","message":"2018-04-21T03:26:37.336Z mediasoup:Channel request succeeded [id:%s]","data":[40891009]}
Apr 21 03:26:37 privcalls-dev-privcalls-app-0-5-0-j75g sfu[438]: {"level":"info","time":"2018-04-21T03:26:37Z","message":"2018-04-21T03:26:37.336Z mediasoup:Channel request succeeded [id:%s]","data":[49946889]}
Apr 21 03:26:37 privcalls-dev-privcalls-app-0-5-0-j75g sfu[438]: {"level":"info","time":"2018-04-21T03:26:37Z","message":"2018-04-21T03:26:37.336Z mediasoup:Producer \"producer.close\" request succeeded"}
Apr 21 03:26:37 privcalls-dev-privcalls-app-0-5-0-j75g sfu[438]: {"level":"info","time":"2018-04-21T03:26:37Z","message":"2018-04-21T03:26:37.336Z mediasoup:Consumer \"consumer.close\" request succeeded"}
Apr 21 03:26:37 privcalls-dev-privcalls-app-0-5-0-j75g sfu[438]: {"level":"info","time":"2018-04-21T03:26:37Z","message":"2018-04-21T03:26:37.336Z mediasoup:WebRtcTransport \"transport.close\" request succeeded"}
Apr 21 03:26:37 privcalls-dev-privcalls-app-0-5-0-j75g sfu[438]: {"level":"info","time":"2018-04-21T03:26:37Z","message":"2018-04-21T03:26:37.336Z mediasoup:WebRtcTransport \"transport.close\" request succeeded"}
Apr 21 03:26:37 privcalls-dev-privcalls-app-0-5-0-j75g sfu[438]: {"level":"info","time":"2018-04-21T03:26:37Z","message":"2018-04-21T03:26:37.563Z mediasoup:ActiveSpeakerDetector emitting \"activespeakerchange\" [peerName:null]"}
Apr 21 03:26:37 privcalls-dev-privcalls-app-0-5-0-j75g sfu[438]: {"level":"info","time":"2018-04-21T03:26:37Z","message":"2018-04-21T03:26:37.816Z mediasoup:Producer getStats()"}
Apr 21 03:26:37 privcalls-dev-privcalls-app-0-5-0-j75g sfu[438]: {"level":"info","time":"2018-04-21T03:26:37Z","message":"2018-04-21T03:26:37.816Z mediasoup:Channel request() [method:%s, id:%s]","data":["producer.getStats",72793950]}
Apr 21 03:26:37 privcalls-dev-privcalls-app-0-5-0-j75g sfu[438]: {"level":"info","time":"2018-04-21T03:26:37Z","message":"2018-04-21T03:26:37.816Z mediasoup:Channel request succeeded [id:%s]","data":[72793950]}
Apr 21 03:26:37 privcalls-dev-privcalls-app-0-5-0-j75g sfu[438]: {"level":"info","time":"2018-04-21T03:26:37Z","message":"2018-04-21T03:26:37.817Z mediasoup:Producer \"producer.getStats\" request succeeded"}
Apr 21 03:26:38 privcalls-dev-privcalls-app-0-5-0-j75g sfu[438]: {"level":"info","time":"2018-04-21T03:26:38Z","message":"2018-04-21T03:26:38.816Z mediasoup:Producer getStats()"}
Apr 21 03:26:38 privcalls-dev-privcalls-app-0-5-0-j75g sfu[438]: {"level":"info","time":"2018-04-21T03:26:38Z","message":"2018-04-21T03:26:38.816Z mediasoup:Channel request() [method:%s, id:%s]","data":["producer.getStats",29010488]}
Apr 21 03:26:38 privcalls-dev-privcalls-app-0-5-0-j75g sfu[438]: {"level":"info","time":"2018-04-21T03:26:38Z","message":"2018-04-21T03:26:38.817Z mediasoup:Channel request succeeded [id:%s]","data":[29010488]}
Apr 21 03:26:38 privcalls-dev-privcalls-app-0-5-0-j75g sfu[438]: {"level":"info","time":"2018-04-21T03:26:38Z","message":"2018-04-21T03:26:38.818Z mediasoup:Producer \"producer.getStats\" request succeeded"}
Apr 21 03:26:39 privcalls-dev-privcalls-app-0-5-0-j75g sfu[438]: {"level":"info","time":"2018-04-21T03:26:39Z","message":"2018-04-21T03:26:39.817Z mediasoup:Producer getStats()"}
Apr 21 03:26:39 privcalls-dev-privcalls-app-0-5-0-j75g sfu[438]: {"level":"info","time":"2018-04-21T03:26:39Z","message":"2018-04-21T03:26:39.818Z mediasoup:Channel request() [method:%s, id:%s]","data":["producer.getStats",21671261]}
Apr 21 03:26:39 privcalls-dev-privcalls-app-0-5-0-j75g sfu[438]: {"level":"info","time":"2018-04-21T03:26:39Z","message":"2018-04-21T03:26:39.818Z mediasoup:Channel request succeeded [id:%s]","data":[21671261]}
Apr 21 03:26:39 privcalls-dev-privcalls-app-0-5-0-j75g sfu[438]: {"level":"info","time":"2018-04-21T03:26:39Z","message":"2018-04-21T03:26:39.819Z mediasoup:Producer \"producer.getStats\" request succeeded"}
Apr 21 03:26:40 privcalls-dev-privcalls-app-0-5-0-j75g sfu[438]: {"level":"info","time":"2018-04-21T03:26:40Z","message":"2018-04-21T03:26:40.819Z mediasoup:Producer getStats()"}
Apr 21 03:26:40 privcalls-dev-privcalls-app-0-5-0-j75g sfu[438]: {"level":"info","time":"2018-04-21T03:26:40Z","message":"2018-04-21T03:26:40.819Z mediasoup:Channel request() [method:%s, id:%s]","data":["producer.getStats",34032067]}
Apr 21 03:26:40 privcalls-dev-privcalls-app-0-5-0-j75g sfu[438]: {"level":"info","time":"2018-04-21T03:26:40Z","message":"2018-04-21T03:26:40.819Z mediasoup:Channel request succeeded [id:%s]","data":[34032067]}
Apr 21 03:26:40 privcalls-dev-privcalls-app-0-5-0-j75g sfu[438]: {"level":"info","time":"2018-04-21T03:26:40Z","message":"2018-04-21T03:26:40.820Z mediasoup:Producer \"producer.getStats\" request succeeded"}
Apr 21 03:26:41 privcalls-dev-privcalls-app-0-5-0-j75g sfu[438]: {"level":"info","time":"2018-04-21T03:26:41Z","message":"2018-04-21T03:26:41.429Z mediasoup:Peer close()"}
Apr 21 03:26:41 privcalls-dev-privcalls-app-0-5-0-j75g sfu[438]: {"level":"info","time":"2018-04-21T03:26:41Z","message":"2018-04-21T03:26:41.429Z mediasoup:Peer _sendNotification() [method:%s]","data":["closed"]}
Apr 21 03:26:41 privcalls-dev-privcalls-app-0-5-0-j75g sfu[438]: {"level":"info","time":"2018-04-21T03:26:41Z","message":"2018-04-21T03:26:41.430Z mediasoup:Producer close()"}
Apr 21 03:26:41 privcalls-dev-privcalls-app-0-5-0-j75g sfu[438]: {"level":"info","time":"2018-04-21T03:26:41Z","message":"2018-04-21T03:26:41.430Z mediasoup:Channel request() [method:%s, id:%s]","data":["producer.close",16882324]}
Apr 21 03:26:41 privcalls-dev-privcalls-app-0-5-0-j75g sfu[438]: {"level":"info","time":"2018-04-21T03:26:41Z","message":"2018-04-21T03:26:41.430Z mediasoup:WebRtcTransport close()"}
Apr 21 03:26:41 privcalls-dev-privcalls-app-0-5-0-j75g sfu[438]: {"level":"info","time":"2018-04-21T03:26:41Z","message":"2018-04-21T03:26:41.430Z mediasoup:Channel request() [method:%s, id:%s]","data":["transport.close",47567651]}
Apr 21 03:26:41 privcalls-dev-privcalls-app-0-5-0-j75g sfu[438]: {"level":"info","time":"2018-04-21T03:26:41Z","message":"2018-04-21T03:26:41.431Z mediasoup:WebRtcTransport close()"}
Apr 21 03:26:41 privcalls-dev-privcalls-app-0-5-0-j75g sfu[438]: {"level":"info","time":"2018-04-21T03:26:41Z","message":"2018-04-21T03:26:41.431Z mediasoup:Channel request() [method:%s, id:%s]","data":["transport.close",10589747]}
Apr 21 03:26:41 privcalls-dev-privcalls-app-0-5-0-j75g sfu[438]: {"level":"info","time":"2018-04-21T03:26:41Z","message":"2018-04-21T03:26:41.440Z mediasoup:Channel request succeeded [id:%s]","data":[16882324]}
Apr 21 03:26:41 privcalls-dev-privcalls-app-0-5-0-j75g sfu[438]: {"level":"info","time":"2018-04-21T03:26:41Z","message":"2018-04-21T03:26:41.440Z mediasoup:Channel request succeeded [id:%s]","data":[47567651]}
Apr 21 03:26:41 privcalls-dev-privcalls-app-0-5-0-j75g sfu[438]: {"level":"info","time":"2018-04-21T03:26:41Z","message":"2018-04-21T03:26:41.440Z mediasoup:Producer \"producer.close\" request succeeded"}
Apr 21 03:26:41 privcalls-dev-privcalls-app-0-5-0-j75g sfu[438]: {"level":"info","time":"2018-04-21T03:26:41Z","message":"2018-04-21T03:26:41.440Z mediasoup:WebRtcTransport \"transport.close\" request succeeded"}
Apr 21 03:26:41 privcalls-dev-privcalls-app-0-5-0-j75g sfu[438]: {"level":"info","time":"2018-04-21T03:26:41Z","message":"2018-04-21T03:26:41.447Z mediasoup:Channel channel ended by the other side"}
Apr 21 03:26:41 privcalls-dev-privcalls-app-0-5-0-j75g sfu[438]: {"level":"warn","time":"2018-04-21T03:26:41Z","message":"2018-04-21T03:26:41.447Z mediasoup:ERROR:Worker child process exited [id:%s, code:%s, signal:%s]","data":["yoveohms#2","SIGSEGV"]}
Apr 21 03:26:41 privcalls-dev-privcalls-app-0-5-0-j75g sfu[438]: {"level":"info","time":"2018-04-21T03:26:41Z","message":"2018-04-21T03:26:41.447Z mediasoup:Worker close()"}
```

Can you provide any context around the `channel ended by the other side` log? I'm curious what  because I have a test running that should give me consistent results but I only see that log occasionally (and at least from what I saw of the last day's logs, both times I saw it, it caused the SIGSEGV or SIGABRT).

**Comment by jmillan** [comment] 2018-04-22 10:06
Hi,

Are you running the latest mediasoup version?

The following assumes that the previous question is affirmative. 

So there's being a crash and here we've got a meaningful log:

` corrupted double-linked list: 0x0000000001bdbd60 `

Do you have the coredump file handy? If you do, please paste here a full backtrace. If not, here is how to get it (If you can reproduce it):

* Enable coredumps in the system: `ulimit -c unlimited`
* *Linux*: check the coredump file generation path: `cat /proc/sys/kernel/core_pattern``
* *Mac*: coredump is generated under: `~/Library/Logs/DiagnosticReports/`

**Comment by jmillan** [comment] 2018-04-22 10:13
Also, compile mediasoup with `make Debug` as documente [here](https://github.com/versatica/mediasoup/blob/master/doc/Building.md#make-debug) in order to get debug information

**Comment by artushin** [comment] 2018-04-22 15:32
Ok, I've enabled core dumps and rebuilt as Debug, and am running with DEBUG=mediasoup:* and MEDIASOUP_BUILDTYPE=Debug.

```
mediasoup/worker/out/Debug/mediasoup-worker orvxghfr#1 --logLevel=debug --logTag=info --logTag=ice --logTag=dlts --logTag=rtp --logTag=srtp --logTag=rtcp --logTag=rbe --logTag=rtx --rtcIPv4=true --rtcIPv6=false --rtcAnnouncedIPv4=35.188.176.254 --rtcMinPort=40000 --rtcMaxPort=44999
mediasoup/worker/out/Debug/mediasoup-worker orvxghfr#2 --logLevel=debug --logTag=info --logTag=ice --logTag=dlts --logTag=rtp --logTag=srtp --logTag=rtcp --logTag=rbe --logTag=rtx --rtcIPv4=true --rtcIPv6=false --rtcAnnouncedIPv4=35.188.176.254 --rtcMinPort=45000 --rtcMaxPort=49997
```

Waiting for a new crash.

**Comment by jmillan** [comment] 2018-04-22 18:29
Thanks

If you want to test that coredumps are generated as expected:

```
pgrep mediasoup
kill -SIGQUIT process_id
```

**Comment by artushin** [comment] 2018-04-24 16:56
@ibc, I don't think so. I just included a longer tail of logs that had a bunch of stats requests. I think the error that occurs at the end is different.

**Comment by ibc** [comment] 2018-04-24 17:02
The stats crash (#196) randomly occurs and it depends on the currently selected simulcast stream and so on. And I see lot of `getStats` calls in your logs. Said in other words, can you reproduce the crash without enabling stats?

**Comment by artushin** [comment] 2018-04-24 20:24
I'm not using simulcast. I can rarely reproduce the crash in the first place it happens so infrequently (I've seen it once or twice a week with a constantly recurring call), so I want to get @jmillan's coredump before I try it with stats turned off (which I might not really be able to do considering how integral stats are to my entire setup).

**Comment by ibc** [comment] 2018-04-24 22:11
Perhaps I said too much. In fact, the crash related to #196 may even happen without simulcast.

**Comment by ibc** [comment] 2018-08-17 17:06
Hi @artushin, were you able to get a core dump?

**Comment by artushin** [comment] 2018-08-17 20:56
Nope, hasn't happened since. Feel free to close the ticket, I'll let you know if it ever happens again.

**Comment by artushin** [comment] 2018-08-17 20:57
I've moved to docker shortly after this issue, so I assume it was environment related.

**Comment by ibc** [comment] 2018-11-06 14:21
Hi @artushin, I assume no news on this and also that this bug was created due to historical bugs in stats generation (2 or 3 that have been already fixed). Closing the issue. Reopen or comment if you experiment it again. Thanks.

**Closed by ibc** 2018-11-06 14:21 UTC
